src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column]
    private ?string $statut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'membre', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

   

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminCrudProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdminCrudProduitController extends AbstractController
{
    #[Route('/admin/crud/produit', name: 'app_admin_crud_produit')]
    public function index(ProduitRepository $repo, EntityManagerInterface $manager): Response
    {   $colonnes = $manager->getClassMetadata(Produit::class)->getFieldNames();
        $produit = $repo->findAll();

        return $this->render('admin_crud_produit/index.html.twig', [
            'colonnes' => $colonnes,
            'produit' => $produit
        ]);
    }
    #[Route('/admin/crud/produit/new', name: 'admin_crud_produit_new')]
    #[Route('/admin/crud/produit/edit/{id}', name: 'admin_crud_produit_edit')]
    public function form(Produit $produit =null, Request $rq, EntityManagerInterface $manager)
    {
         if(!$produit){
            $produit = new Produit;
            $produit->setDateEnregistrement(new \DateTime());
        }
        $form = $this->createForm(ProduitType::class, $produit);

        $form->handleRequest($rq);

        if ($form->isSubmitted() && $form->isValid()){
            $manager->persist($produit);
            $manager->flush();
          

            return $this->redirectToRoute('app_admin_crud_produit');
        }
        return $this->renderForm('admin_crud_produit/form.html.twig', [
            'form' => $form,
            'editMode' => $produit->getId() != NULL
        ]);
    }
    #[Route('/admin/crud/produit/delete/{id}', name: 'admin_crud_produit_delete')]
    public function delete(Produit $produit = null, EntityManagerInterface $manager)
    {
        if ($produit) {
            $manager->remove($produit);
            $manager->flush();
            
        }
        return $this->redirectToRoute('app_admin_crud_produit');
    }
}

templates/admin_crud_produit/form.html.twig
{% extends "base.html.twig" %}

{% block title %}Admin | Formulaire Produit
{% endblock %}

{% block body %}

	<h1 class="display-4 text-center my-4">

		{% if editMode %}
			BACKOFFICE | Edition produit 
		{% else %}
			BACKOFFICE | Création produit
		{% endif %}

	</h1>

	{{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}

	{{ form_row(form.titre) }}
	{{ form_row(form.description) }}
	{{ form_row(form.couleur ) }}
	{{ form_row(form.taille) }}
    {{ form_row(form.collection) }}
	{{ form_row(form.photo) }}
	{{ form_row(form.prix) }}
    {{ form_row(form.stock) }}
    

	<button class="btn btn-primary my-2" type="submit">

		{% if editMode %}
			Enregistrer les modifications
		{% else %}
			Enregistrer
		{% endif %}

	</button>

	{{ form_end(form) }}


{% endblock %}

templates/admin_crud_produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin Produit
{% endblock %}

{% block body %}

	<h1 class="text-center">Gestion des Produit</h1>

	<a href="{{ path('admin_crud_produit_new') }}" class="btn btn-success my-3">Ajouter un produit</a>

	<table class="table table-bordered text-center">
		<thead>
			<tr>
				{% for data in colonnes %}
					{% if data != "id" %}
						<th>{{ data }}</th>
					{% endif %}
				{% endfor %}
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for data in produit %}
				<tr>
					<td>{{ data.titre }}</td>
                    <td>{{ data.description }}</td>
                    <td>{{ data.couleur }}</td>
                    <td>{{ data.taille }}</td>
                    <td>{{ data.collection }}</td>
                    <td><img src="{{ data.photo }}" alt="Photo" style="width: 150px;"></td>
					<td>{{ data.prix }}€</td>
					<td>{{ data.stock }}</td>
				    <td>{{ data.dateEnregistrement|date('d/m/Y à H:i:s') }}</td>
					<td>
						<a href="{{ path('admin_crud_produit_edit', {'id': data.id}) }}" class="text-dark">
							<i class="fas fa-edit fa-lg"></i>
						</a>

						<a onclick="return confirm('Voulez-vous supprimer  ?')" href="{{ path('admin_crud_produit_delete', {'id': data.id}) }}" class="text-dark">
							<i class="fas fa-trash-alt fa-lg"></i>
						</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>

	</table>

{% endblock %}